### ISSUE TITLE
Nesne başvurusu bir nesnenin örneğine ayarlanmadı. Hatası

### ISSUE THREAD

**Issue by furkanzkafka** [OzdemirFurkan/MVC#1]
ProductController.cs class-ının 72.satırında 

>     [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Urunler model)
        {
            if (ModelState.IsValid)
            {
                odevDB db = new odevDB();
                var data = db.Urunlers.FirstOrDefault(x => x.urunID == model.urunID);

                data.urunAd = model.urunAd; (Hata aldigimiz satir)
                data.urunFiyat = model.urunFiyat;

                bool IsSuccess = db.SaveChanges() > 0 ? false : true;
                ViewBag.Message = IsSuccess == true ? "Guncellendi" : "Tekrar Deneyiniz...";
            }

            return View(model);
        }

>

**Comment by coshkun** [comment]
Furkan ayarlardan Contributor.lere gir.. beni ordan katılımcı olarak ekle.. fork atarsam kopya cıkartıyor, geriye  commit yapamam.

**Comment by furkanzkafka** [comment]
ProductController.cs icerisindeki Edit bloğunun Viewine "@Html.HiddenFor(x => x.urunID)" kodunu ekleyeren sorunu çözdük
